### ISSUE TITLE
App Terminating with exception before running 

### ISSUE THREAD

**Issue by vamsi981** [wi3land/ionic-appauth-capacitor-demo#3] opened 2019-05-23 09:55 UTC
Hi @wi3land ,

i tried the same app which you have share and ended up with below issue 

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

*** First throw call stack:

(

0   CoreFoundation                      0x0000000109eb81bb __exceptionPreprocess + 331

1   libobjc.A.dylib                     0x00000001074bd735 objc_exception_throw + 48

2   CoreFoundation                      0x0000000109eb8015 +[NSException raise:format:] + 197

3   Foundation                          0x0000000106ea0e79 -[NSBundle initWithURL:] + 87

4   Foundation                          0x0000000106ea0f28 +[NSBundle bundleWithURL:] + 45

5   CordovaPlugins                      0x00000001062d1377 __34+[SAMKeychainQuery errorWithCode:]_block_invoke + 183

6   libdispatch.dylib                   0x000000011128c602 _dispatch_client_callout + 8

7   libdispatch.dylib                   0x000000011128e0c4 _dispatch_once_callout + 66

8   CordovaPlugins                      0x00000001062d0bad +[SAMKeychainQuery errorWithCode:] + 157

9   CordovaPlugins                      0x00000001062d03d8 -[SAMKeychainQuery fetch:] + 568

10  CordovaPlugins                      0x00000001062d1f79 __21-[SecureStorage get:]_block_invoke + 169

11  libdispatch.dylib                   0x000000011128b595 _dispatch_call_block_and_release + 12

12  libdispatch.dylib                   0x000000011128c602 _dispatch_client_callout + 8

13  libdispatch.dylib                   0x000000011128f064 _dispatch_queue_override_invoke + 1028

14  libdispatch.dylib                   0x000000011129d00a _dispatch_root_queue_drain + 351

15  libdispatch.dylib                   0x000000011129d9af _dispatch_worker_thread2 + 130

16  libsystem_pthread.dylib             0x0000000111678169 _pthread_wqthread + 1387

17  libsystem_pthread.dylib             0x0000000111677be9 start_wqthread + 13

)

libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by wi3land** [comment] 2019-06-02 17:57
Hi sorry i have been busy the past view weeks. I am using capacitors App feature instead of custom URL schemes in the capacitor demo. I never ran it on iOS as I didn't have a Mac to hand.

Apparently on iOS you need to configure the info.plist URL scheme yourself. Capacitor does not add this in automatically like they do on Android.

Please see the URL below for more info on what needs to be done.
https://capacitor.ionicframework.com/docs/apis/app

This is a duplicate of a previous issue and fixed the problem.

**Comment by wi3land** [comment] 2019-06-02 17:58
Duplicate of #2

**Closed by wi3land** 2019-06-02 17:58 UTC
